## rabbitmq
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.virtual-host=testhost
#spring.rabbitmq.username=admin
#spring.rabbitmq.password=admin
#
#spring.rabbitmq.publisher-returns=true
## 对 rabbitmqTemplate 进行监听,当消息由于server的原因无法到达queue时，就会被监听到，以便执行ReturnCallback方法
## 默认为false,Server端会自动删除不可达消息
#spring.rabbitmq.template.mandatory=true
#
## 消费端手动确认
#spring.rabbitmq.listener.simple.acknowledge-mode=manual
## 并发消费
#spring.rabbitmq.listener.simple.concurrency=1
#spring.rabbitmq.listener.simple.max-concurrency=1

spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: testhost
    username: admin
    password: admin
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1